OPENAI_API_KEY = ""

SPEECH_ASSESSMENT_APPID=''
SPEECH_ASSESSMENT_APISecret=''
SPEECH_ASSESSMENT_APIKey=''

BAIDU_TRANSLATION_APPID = ''
BAIDU_TRANSLATION_APPKEY = ''

D_ID_TALK_API_KEY = ""

IFLY_REAL_TIME_TRANSCRITION_API_ID = ""
IFLY_REAL_TIME_TRANSCRITION_API_KEY = ""

Tencent_SecretId=""
Tencent_SecretKey=""

DIFY_API_KEY_WRITING = ''
DIFY_API_KEY_SPEAKING = ""
